default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: book_catalog_development

test:
  <<: *default
  database: book_catalog_test
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>

production:
  <<: *default
  database: book_catalog_production
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: book_catalog
